workerman:
    runtime_dir: '%kernel.project_dir%/var'
    pid_file: '%kernel.project_dir%/var/run/workerman.pid'
    log_file: '%kernel.project_dir%/var/log/workerman.log'
    stdout_file: '%kernel.project_dir%/var/log/workerman.stdout.log'
    stop_timeout: 2
    cache_warmup_timeout: 30

    servers:
        -   name: slop-driven-development
            listen: http://0.0.0.0:8080
            processes: 4
            reuse_port: true

    build:
        exclude_patterns:
            - '#/Tests?/#'
            - '#/tests?/#'
            - '#/docs?/#'
            - '#/Documentation/#'
            - '#/doc/#'
            - '#/examples/#'
            - '#\.md$#'
            - '#\.rst$#'
            - '#CHANGELOG#'
            - '#CHANGE_LOG#'
            - '#FAQ#'
            - '#CONTRIBUTING#'
            - '#\.gitignore$#'
            - '#Makefile$#'
            - '#phpunit#'
            - '#\.github/#'
        exclude_files:
            - source
            - buildroot
            - pkgroot
            - downloads
            - log
            - spc
            - spc.tar.gz
        sfx:
            file: '%kernel.project_dir%/buildroot/bin/micro.sfx'
            sha256: '91c8ca0bb6a80c52f7e29d3c7e50c69e9e7b996f9bed7df3a128b025f82b7cf3'

    reload_strategy:
        exception:
            active: true
            allowed_exceptions:
                - Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
        max_requests:
            active: true
            requests: 1000
            dispersion: 20
        file_monitor:
            active: false
        memory:
            active: false
        always:
            active: false
