parameters:
    default_lang: 'pl'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\:
        resource: '%kernel.project_dir%/src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\ArticleRepository:
        arguments:
            $contentDir: '%kernel.project_dir%/content'

    App\Service\MarkdownParser:

    App\Twig\InlineAssetExtension:
        arguments:
            $publicDir: '%kernel.project_dir%/public'

    App\Command\ContentValidateCommand:
        arguments:
            $contentDir: '%kernel.project_dir%/content'
